// vue/mgr/src/components/page/Login.vue
<template>
    <div class="login-wrap">
        <div class="ms-login">
            <div class="ms-title">后台管理系统</div>
            <el-form :model="ruleForm" :rules="rules" ref="ruleForm" label-width="0px" class="ms-content">
                <el-form-item prop="name">
                    <el-input v-model="ruleForm.name" placeholder="请输入用户名">
                        <el-button slot="prepend" icon="el-icon-lx-people"></el-button>
                    </el-input>
                </el-form-item>
                <el-form-item prop="pwd">
                    <el-input type="password" placeholder="请输入密码" v-model="ruleForm.pwd" @keyup.enter.native="submitForm('ruleForm')">
                        <el-button slot="prepend" icon="el-icon-lx-lock"></el-button>
                    </el-input>
                </el-form-item>
                <el-form-item prop="vcode" v-show="is_show_vcode">
                    <el-input placeholder="请输入验证码" v-model="ruleForm.vcode" maxlength="10" @keyup.enter.native="submitForm('ruleForm')">
                        <el-button slot="prepend" icon="el-icon-lx-info"></el-button>
                    </el-input>
                    <img v-if="is_show_vcode" ref="vcode_img" class="vcode-img" :src="vcode_img" @click="vcodeUpdate($event)" />
                </el-form-item>
                <div class="login-btn">
                    <el-button type="primary" @click="submitForm('ruleForm')">登录</el-button>
                </div>

            </el-form>
        </div>
    </div>
</template>

<script>
    import { cfg } from '../common/common.js';

    export default {
        data() {
            return {
                ruleForm: {
                    name: '',
                    pwd: '',
                    vcode: ''
                },
                rules: {
                    name: [
                        { required: true, message: '请输入用户名', trigger: 'blur' }
                    ],
                    pwd: [
                        { required: true, message: '请输入密码', trigger: 'blur' }
                    ]
                },
                is_show_vcode: false,
                vcode_img: cfg.web_server_root + "index/getvcode"
            }
        },
        created() {
            document.title = cfg.web_title;
        },
        methods: {
            submitForm(formName) {
                var that = this;

                this.$refs[formName].validate((valid) => {
                    if (valid) {
                        that.$axios.post(cfg.web_server_root + "index/login", {
                            name: that.ruleForm.name,
                            pwd: that.ruleForm.pwd,
                            vcode: that.ruleForm.vcode
                        }).then((response) => {
                            if(response.data.code == 0) {
                                localStorage.setItem('user_name', response.data.data.name);
                                localStorage.setItem('user_id', response.data.data.id);
                                that.$router.push('/');
                                //console.log(response.data.data);
                            }
                            else if(response.data.code == 2) {
                                //需要输入验证码
                                that.ruleForm.vcode = "";
                                that.is_show_vcode = true;
                            }
                            else if(response.data.code == 3) {
                                //验证码错误
                                that.$alert(response.data.msg, '提示', {
                                    confirmButtonText: '确定',
                                    type: 'error'
                                });
                                that.ruleForm.vcode = "";
                                that.$refs.vcode_img.click();
                            }
                            else {
                                that.is_show_vcode = false;
                                that.$alert(response.data.msg, '提示', {
                                    confirmButtonText: '确定',
                                    type: 'error'
                                });
                            }
                        }).catch((error) => {
                            that.$alert(error, '提示', {
                                confirmButtonText: '确定',
                                type: 'error'
                            });
                        });
                    }
                    else {
                        that.$alert('请正确输入完整信息', '提示', {
                            confirmButtonText: '确定',
                            type: 'error'
                        });
                        return false;
                    }
                });
            },
            vcodeUpdate(event) {
                var el = event.currentTarget;
                el.src = this.vcode_img + "?dt=" + Math.random();
            }
        }
    }
</script>

<style scoped>
    .login-wrap{
        position: relative;
        width:100%;
        height:100%;
        background-image: url(../../assets/login-bg.jpg);
        background-size: 100%;
    }
    .ms-title{
        width:100%;
        line-height: 50px;
        text-align: center;
        font-size:20px;
        color: #666;
        border-bottom: 1px solid #ddd;
    }
    .ms-login{
        position: absolute;
        left:50%;
        top:50%;
        width:350px;
        margin:-190px 0 0 -175px;
        border-radius: 5px;
        background: rgba(255,255,255, 0.3);
        overflow: hidden;
    }
    .ms-content{
        padding: 30px 30px;
    }
    .login-btn{
        text-align: center;
    }
    .login-btn button{
        width:100%;
        height:36px;
        margin-bottom: 10px;
    }
    .vcode-img {
        display: block;
        position: absolute;
        width: 118px;
        top: 3px;
        left: 171px;
        cursor: pointer;
    }
</style>

// react/mgr/src/components/pages/Login.jsx

import React from 'react';
import { Form, Icon, Input, Button, message } from 'antd';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { fetchData, receiveData } from '@/action';
import axios from 'axios';

import { cfg, func } from '../../common';

const FormItem = Form.Item;

class Login extends React.Component {
	constructor(props) {
		super(props);
    	
    	this.state = {
    		css_vcode_div: {
    			display: 'none'
    		},
    		css_vcode_img: {
    			display: "block",
				position: "absolute",
				width: "118px",
				top: "-6px",
				left: "129px",
				cursor: "pointer",
    		},
    		vcode_img: cfg.web_server_root + "index/getvcode"
    	};
    	
    	document.title = cfg.web_title;
	}

    componentWillMount() {
        
    }
    componentDidUpdate(prevProps) { // React 16.3+弃用componentWillReceiveProps
        
    }
    handleSubmit = (e) => {
        e.preventDefault();
        
        var that = this;
        this.props.form.validateFields((err, values) => {
            if (!err) {
                
                axios.post(cfg.web_server_root + "index/login", {
                    name: values.userName,
                    pwd: values.password,
                	vcode: values.vcode
                }).then(function (response) {
					
					if(response.data.code === 0) {
                        localStorage.setItem('user_name', response.data.data.name);
                        localStorage.setItem('user_id', response.data.data.id);
                        
                        that.props.history.push('/app/dashboard/index');
                    }
                    else if(response.data.code === 2) {
                        //需要输入验证码
                        values.vcode = "";
                        that.setState({
                        	css_vcode_div: {
								display: 'block'
							}
                        });
                    }
                    else if(response.data.code === 3) {
                        //验证码错误
                        message.info(response.data.msg);
                        
                        values.vcode = "";
                        that.refs.vcode_img.click();
                    }
                    else {
                         message.info(response.data.msg);
                    }
				}).catch(function (error) {
					console.log(error);
				});
                
            }
        });
    };
    vcodeUpdate = (e) => {
    	e.preventDefault();
    	
    	var el = e.currentTarget;
        el.src = this.state.vcode_img + "?dt=" + Math.random();
    };
    
    render() {
        const { getFieldDecorator } = this.props.form;
        return (
            <div className="login">
                <div className="login-form" >
                    <div className="login-logo">
                        <span>后台管理系统</span>
                    </div>
                    <Form onSubmit={this.handleSubmit} style={{maxWidth: '300px'}}>
                        <FormItem>
                            {getFieldDecorator('userName', {
                                rules: [{ required: true, message: '请输入用户名!' }],
                            })(
                                <Input prefix={<Icon type="user" style={{ fontSize: 13 }} />} placeholder="请输入用户名" />
                            )}
                        </FormItem>
                        <FormItem>
                            {getFieldDecorator('password', {
                                rules: [{ required: true, message: '请输入密码!' }],
                            })(
                                <Input prefix={<Icon type="lock" style={{ fontSize: 13 }} />} type="password" placeholder="请输入密码" />                                
                            )}                            
                        </FormItem>
                        <FormItem style={this.state.css_vcode_div}>
                            {getFieldDecorator('vcode', {
                                rules: [
                                	{ max: 6, message: '输入内容过长!' }
                                ],
                            })(
                                <Input prefix={<Icon type="picture" style={{ fontSize: 13 }} />} placeholder="请输入验证码" />
                            )}
                            <img ref="vcode_img" alt="验证码" style={this.state.css_vcode_img} src={this.state.vcode_img} onClick={this.vcodeUpdate} />
                        </FormItem>
                        <FormItem>
                            <Button type="primary" htmlType="submit" className="login-form-button" style={{width: '100%'}}>登录</Button>                            
                        </FormItem>
                    </Form>
                </div>
            </div>
        );
    }
}

const mapStateToPorps = state => {
    const { auth } = state.httpData;
    return { auth };
};
const mapDispatchToProps = dispatch => ({
    fetchData: bindActionCreators(fetchData, dispatch),
    receiveData: bindActionCreators(receiveData, dispatch)
});


export default connect(mapStateToPorps, mapDispatchToProps)(Form.create()(Login));
