// vue/mgr/src/components/page/Dashboard.vue
<template>
    <div>
        <el-row :gutter="20">
            <el-col :span="24">
                <el-card shadow="hover" style="min-height: 400px;">
                    <div slot="header" class="clearfix">
                        <span>主机探针</span>
                    </div>
                    <div>
                        <table id="viewtable">
							<tr>
								<td class="viewtable_title">服务器（IP）</td>
								<td v-text="server_info.server_name"></td>
							</tr>
							<tr>
								<td class="viewtable_title">操作系统</td>
								<td v-text="server_info.os"></td>
							</tr>
							<tr>
								<td class="viewtable_title">服务器软件</td>
								<td v-text="server_info.server_software"></td>
							</tr>
							<tr>
								<td class="viewtable_title">PHP版本</td>
								<td v-text="server_info.php_version"></td>
							</tr>
							<tr>
								<td class="viewtable_title">ThinkPHP版本</td>
								<td v-text="server_info.thinkphp_ver"></td>
							</tr>
							<tr>
								<td class="viewtable_title">上传文件大小</td>
								<td v-text="server_info.upload_file_status"></td>
							</tr>
							<tr>
								<td class="viewtable_title">脚本超时</td>
								<td v-text="server_info.max_execution_time"></td>
							</tr>
							<tr>
								<td class="viewtable_title">网站路径</td>
								<td v-text="server_info.document_root"></td>
							</tr>
							<tr>
								<td class="viewtable_title">服务器时间</td>
								<td v-text="server_info.now"></td>
							</tr>
						</table>
                    </div>
                </el-card>
            </el-col>
        </el-row>
    </div>
</template>

<script>
    import bus from '../common/bus';
    import { cfg } from '../common/common.js';

    export default {
        name: 'dashboard',
        data() {
            return {
                server_info: {
                    server_name: '',
			        os: '',
			        server_software: '',
			        php_version: '',
			        upload_file_status: '',
			        max_execution_time: '',
			        document_root: '',
			        now: '',
			        thinkphp_ver: '',
                }
            }
        },
        methods: {

        },
        created() {
            document.title = cfg.web_title;

            var that = this;
            that.$axios.get(cfg.web_server_root + "other/serverInfo").then((response) => {
                if(response.data.code == 0) {
                    that.server_info = response.data.data;
                }
                else {
                    that.$router.push('/login');
                }
            }).catch((error) => {
                that.$alert(error, '提示', {
                    confirmButtonText: '确定',
                    type: 'error',
                });
            });
        }
    }

</script>


<style scoped>
#viewtable {
    width: 75%;
    color: #999;
}
#viewtable .viewtable_title {
	width: 30%;
	height: 30px;
	text-align: right;
	padding-right: 40px;
	color: #333;
}
</style>

// react/mgr/src/components/dashboard/Dashboard.jsx

import React from 'react';
import { Row, Col, Card, Timeline, Icon, Table, message } from 'antd';
import BreadcrumbCustom from '../BreadcrumbCustom';
import { cfg, func } from '../../common';

import axios from 'axios';

import '../../style/css/dashboard/Dashboard.css';

export default class Dashboard extends React.Component {
	constructor(props) {
		super(props);
    	
    	this.state = {
    		server_info: {
    			server_name: "",
    			os: "",
    			server_software: "",
    			php_version: "",
    			thinkphp_ver: "",
    			upload_file_status: "",
    			max_execution_time: "",
    			document_root: "",
    			now: ""
    		}
    	};
    	
    	document.title = cfg.web_title;
	}
	
	componentDidMount() {
		var that = this;
        axios.get(cfg.web_server_root + "other/serverInfo").then(function (response) {
        	if(response.data.code === 0) {
            	that.setState({
            		server_info: response.data.data
            	});
            }
            else {
            	message.error(response.data.msg);
            	that.props.history.push('/login');
            }
        }).catch(function (error) {
            message.error(error);
        });
	}

    render() {
    
        return (
            <div>
                <BreadcrumbCustom first="系统首页" />
                <Row gutter={10}>
                    <Col className="gutter-row" md={24}>
                        <div className="gutter-box">
                            <Card bordered={false}>
                                <h3 id="dashboard_title_1">主机探针</h3>
                                <table id="dashboard_viewtable">
									<tr>
										<td class="viewtable_title">服务器（IP）</td>
										<td>{this.state.server_info.server_name}</td>
									</tr>
									<tr>
										<td class="viewtable_title">操作系统</td>
										<td>{this.state.server_info.os}</td>
									</tr>
									<tr>
										<td class="viewtable_title">服务器软件</td>
										<td>{this.state.server_info.server_software}</td>
									</tr>
									<tr>
										<td class="viewtable_title">PHP版本</td>
										<td>{this.state.server_info.php_version}</td>
									</tr>
									<tr>
										<td class="viewtable_title">ThinkPHP版本</td>
										<td>{this.state.server_info.thinkphp_ver}</td>
									</tr>
									<tr>
										<td class="viewtable_title">上传文件大小</td>
										<td>{this.state.server_info.upload_file_status}</td>
									</tr>
									<tr>
										<td class="viewtable_title">脚本超时</td>
										<td>{this.state.server_info.max_execution_time}</td>
									</tr>
									<tr>
										<td class="viewtable_title">网站路径</td>
										<td>{this.state.server_info.document_root}</td>
									</tr>
									<tr>
										<td class="viewtable_title">服务器时间</td>
										<td>{this.state.server_info.now}</td>
									</tr>
								</table>
						
                            </Card>
                        </div>
                    </Col>
                </Row>                
            </div>
        )
    }
}
